///////////////////////////////////////////////////////////
//  Cat.cs
//  Implementation of the Class Cat
//  Generated by Enterprise Architect
//  Created on:      08-6月-2021 8:53:21
//  Original author: Ren
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ObserverDemo;
namespace ObserverDemo
{
    public class Cat : Subject
    {
        public override void Call()
        {
            Console.WriteLine("猫发出了叫声");
            base.Call();
        }

    }//end Cat

}//end namespace ObserverDemo