///////////////////////////////////////////////////////////
//  IObserver.cs
//  Implementation of the Interface IObserver
//  Generated by Enterprise Architect
//  Created on:      08-6ÔÂ-2021 8:53:26
//  Original author: Ren
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace ObserverDemo
{
    public interface IObserver
    {

        void Action();
    }//end IObserver

}//end namespace ObserverDemo