///////////////////////////////////////////////////////////
//  Master.cs
//  Implementation of the Class Master
//  Generated by Enterprise Architect
//  Created on:      08-6月-2021 8:53:24
//  Original author: Ren
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ObserverDemo;
namespace ObserverDemo
{
    public class Master : IObserver
    {

        public void Action()
        {
            Console.WriteLine("主人被唤醒了！");
        }

    }//end Master

}//end namespace ObserverDemo