///////////////////////////////////////////////////////////
//  Mouse.cs
//  Implementation of the Class Mouse
//  Generated by Enterprise Architect
//  Created on:      08-6月-2021 8:53:23
//  Original author: Ren
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ObserverDemo;
namespace ObserverDemo
{
    public class Mouse : IObserver
    {

        public void Action()
        {
            Console.WriteLine("老鼠被吓跑了！");
        }

    }//end Mouse

}//end namespace ObserverDemo