///////////////////////////////////////////////////////////
//  Subject.cs
//  Implementation of the Class Subject
//  Generated by Enterprise Architect
//  Created on:      08-6ÔÂ-2021 8:53:19
//  Original author: Ren
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ObserverDemo;
namespace ObserverDemo
{
    public class Subject
    {

        private IList<IObserver> observers = new List<IObserver>();

        public void AddObserver(IObserver obs)
        {
            observers.Add(item: obs);
        }

        public virtual void Call()
        {
            foreach (var item in observers)
            {
                item.Action();
            }
        }

        public int RemoveObserver(IObserver obs)
        {

            return 0;
        }

    }//end Subject

}//end namespace ObserverDemo