///////////////////////////////////////////////////////////
//  Coffee.cs
//  Implementation of the Class Coffee
//  Generated by Enterprise Architect
//  Created on:      18-5月-2021 9:51:30
//  Original author: Ren
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
namespace CofeeDecoratorDemo
{
    public abstract class Coffee
    {

        private string name;
        private float price;

        /// <summary>
        /// 抽象方法计算价格
        /// </summary>
        /// <param name="number"></param>
        /// <returns></returns>
        public abstract float Cacl(int number);

        public string Name
        {
            get
            {
                return name;
            }
            set
            {
                name = value;
            }
        }

        public virtual float Price
        {
            get
            {
                return price;
            }
            set
            {
                price = value;
            }
        }

    }//end Coffee

}//end namespace CofeeDecoratorDemo