///////////////////////////////////////////////////////////
//  DarkRoast.cs
//  Implementation of the Class DarkRoast
//  Generated by Enterprise Architect
//  Created on:      18-5月-2021 9:51:37
//  Original author: Ren
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

using CofeeDecoratorDemo;
namespace CofeeDecoratorDemo
{
    public class DarkRoast : Coffee
    {
        /// <summary>
        /// 计算价格
        /// </summary>
        /// <param name="number"></param>
        /// <returns>返回价格</returns>
        public override float Cacl(int number)
        {
            Console.WriteLine("您点了{0}杯重烘培咖啡！", number);
            return base.Price * number;
        }

    }//end DarkRoast

}//end namespace CofeeDecoratorDemo