///////////////////////////////////////////////////////////
//  Espresso.cs
//  Implementation of the Class Espresso
//  Generated by Enterprise Architect
//  Created on:      18-5ÔÂ-2021 9:51:33
//  Original author: Ren
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using CofeeDecoratorDemo;
namespace CofeeDecoratorDemo
{
    public class Espresso : Coffee
    {
        public override float Cacl(int number)
        {
            return number * this.Price;
        }

    }//end Espresso

}//end namespace CofeeDecoratorDemo