///////////////////////////////////////////////////////////
//  HouseBlend.cs
//  Implementation of the Class HouseBlend
//  Generated by Enterprise Architect
//  Created on:      18-5月-2021 9:51:35
//  Original author: Ren
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using CofeeDecoratorDemo;
namespace CofeeDecoratorDemo
{
    public class HouseBlend : Coffee
    {
        /// <summary>
        /// 完成价格计算
        /// </summary>
        /// <param name="number"></param>
        /// <returns>返回价格</returns>
        public override float Cacl(int number)
        {
            return number * this.Price;
        }

    }//end HouseBlend

}//end namespace CofeeDecoratorDemo