///////////////////////////////////////////////////////////
//  Mocha.cs
//  Implementation of the Class Mocha
//  Generated by Enterprise Architect
//  Created on:      18-5月-2021 9:51:40
//  Original author: Ren
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using CofeeDecoratorDemo;
namespace CofeeDecoratorDemo
{
    public class Mocha : Decorator
    {

        /// <summary>
        /// 和父类一致的构造函数,给父类的构造函数传入参数coffee,完成注入
        /// </summary>
        /// <param name="coffee"></param>
        public Mocha(Coffee coffee) : base(coffee)
        {

        }

        public override float Cacl(int number)
        {

            //return (this.Price + base.Price) * number;
            return base.Cacl(number) + this.Price;
        }
        /// <summary>
        /// 设置或获取牛奶的价格
        /// </summary>
        public override float Price { get; set; }
    }//end Mocha

}//end namespace CofeeDecoratorDemo