///////////////////////////////////////////////////////////
//  Whip.cs
//  Implementation of the Class Whip
//  Generated by Enterprise Architect
//  Created on:      18-5月-2021 9:51:41
//  Original author: Ren
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using CofeeDecoratorDemo;
namespace CofeeDecoratorDemo
{
    public class Whip : Decorator
    {
        /// <summary>
        /// 和父类一致的构造函数,给父类的构造函数传入参数coffee,完成注入
        /// </summary>
        /// <param name="coffee"></param>
        public Whip(Coffee coffee) : base(coffee)
        {

        }

        /// <summary>
        /// 计算价格
        /// </summary>
        /// <param name="number"></param>
        /// <returns>返回价格</returns>
        public override float Cacl(int number)
        {

            //return (this.Price + base.Price) * number;
            float allMoney = base.Cacl(number) + this.Price * number;
            Console.WriteLine("添加了奶泡！");
            return allMoney;
        }

    }//end Whip

}//end namespace CofeeDecoratorDemo