///////////////////////////////////////////////////////////
//  IScoreOperation.cs
//  Implementation of the Interface IScoreOperation
//  Generated by Enterprise Architect
//  Created on:      07-5月-2021 11:18:51
//  Original author: Ren
///////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
namespace GradeManagementDemo
{
    public interface IScoreOperation
    {
        /// <summary>
        /// 定义用与查询的方法
        ///     1.传入所有数据
        ///     2.传入需要查询的值
        /// </summary>
        int Search(int[] allGrade, int id);

        /// <summary>
        /// 传入所有数据，然后将该数组进行排序，排序后仍放入该数组中
        /// </summary>
        void Sort(int[] allGrade);
    }//end IScoreOperation

}//end namespace GradeManagementDemo