///////////////////////////////////////////////////////////
//  BorderDecorator.cs
//  Implementation of the Class BorderDecorator
//  Generated by Enterprise Architect
//  Created on:      21-5月-2021 11:47:21
//  Original author: Ren
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using VisualComponentDemo;
namespace VisualComponentDemo
{
    public class BorderDecorator : ComponentDecorator
    {

        private string color;


        public BorderDecorator(VisualComponent component) : base(component)
        {
            this.color = "#00acec";
        }

        public string Color
        {
            get
            {
                return color;
            }
            set
            {
                color = value;
            }
        }

        /// <summary>
        /// 这里进行生成
        /// </summary>
        public override void Display()
        {
            //这里调用父类的生成方法
            base.Display();
            //这里添加装边框的装饰方法
            SetBorder();
            Console.WriteLine("边框装饰添加完成!");
        }

        /// <summary>
        /// 这里进行边框的装饰方法
        /// </summary>
        public void SetBorder()
        {
            Console.WriteLine("在这里生成了指定的Border(边框)!您的边框的颜色为:{0}", color);
        }

    }//end BorderDecorator

}//end namespace VisualComponentDemo