///////////////////////////////////////////////////////////
//  ComponentDecorator.cs
//  Implementation of the Class ComponentDecorator
//  Generated by Enterprise Architect
//  Created on:      21-5ÔÂ-2021 11:47:16
//  Original author: Ren
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using VisualComponentDemo;
namespace VisualComponentDemo
{
    public class ComponentDecorator : VisualComponent
    {

        private VisualComponent visualComponent;
        public ComponentDecorator(VisualComponent component)
        {
            this.visualComponent = component;
        }

        public override void Display()
        {
            visualComponent.Display();
        }

    }//end ComponentDecorator

}//end namespace VisualComponentDemo