///////////////////////////////////////////////////////////
//  ListBox.cs
//  Implementation of the Class ListBox
//  Generated by Enterprise Architect
//  Created on:      21-5月-2021 11:47:13
//  Original author: Ren
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using VisualComponentDemo;
namespace VisualComponentDemo
{
    public class ListBox : VisualComponent
    {

        public override void Display()
        {
            Console.WriteLine("生成ListBox组件!");
        }

    }//end ListBox

}//end namespace VisualComponentDemo