///////////////////////////////////////////////////////////
//  ScrollBarDecorator.cs
//  Implementation of the Class ScrollBarDecorator
//  Generated by Enterprise Architect
//  Created on:      21-5月-2021 11:47:18
//  Original author: Ren
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using VisualComponentDemo;
namespace VisualComponentDemo
{
    public class ScrollBarDecorator : ComponentDecorator
    {

        public ScrollBarDecorator(VisualComponent component) : base(component)
        {

        }

        public override void Display()
        {
            //这里调用父类的生成方法
            base.Display();
            //这里添加装饰器
            SetScrollBar();
            Console.WriteLine("滚动条装饰添加完成!");
        }
        /// <summary>
        /// 这里添加装饰的功能
        /// </summary>
        public void SetScrollBar()
        {
            Console.WriteLine("在这里生成了指定的ScrollBar(滚动条)!");
        }

    }//end ScrollBarDecorator

}//end namespace VisualComponentDemo