///////////////////////////////////////////////////////////
//  TextBox.cs
//  Implementation of the Class TextBox
//  Generated by Enterprise Architect
//  Created on:      21-5月-2021 11:47:11
//  Original author: Ren
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using VisualComponentDemo;
namespace VisualComponentDemo
{
    public class TextBox : VisualComponent
    {
        /// <summary>
        /// 生成TextBox组件
        /// </summary>
        public override void Display()
        {
            Console.WriteLine("生成TextBox组件");
        }

    }//end TextBox

}//end namespace VisualComponentDemo