///////////////////////////////////////////////////////////
//  VisualComponent.cs
//  Implementation of the Class VisualComponent
//  Generated by Enterprise Architect
//  Created on:      21-5月-2021 11:47:04
//  Original author: Ren
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace VisualComponentDemo
{
    public abstract class VisualComponent
    {

        private int id;
        private string text;
        private string title;

        /// <summary>
        /// 声明抽象方法，生成组件，在子类进行生成组件
        /// </summary>
        public abstract void Display();

        public int Id
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }

        public string Text
        {
            get
            {
                return text;
            }
            set
            {
                text = value;
            }
        }

        public string Title
        {
            get
            {
                return title;
            }
            set
            {
                title = value;
            }
        }

    }//end VisualComponent

}//end namespace VisualComponentDemo