///////////////////////////////////////////////////////////
//  Windows.cs
//  Implementation of the Class Windows
//  Generated by Enterprise Architect
//  Created on:      21-5月-2021 11:47:08
//  Original author: Ren
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using VisualComponentDemo;
namespace VisualComponentDemo
{
    public class Windows : VisualComponent
    {
        /// <summary>
        /// 生成Windows组件
        /// </summary>
        public override void Display()
        {
            Console.WriteLine("成功生成Windows组件！");
        }

    }//end Windows

}//end namespace VisualComponentDemo