///////////////////////////////////////////////////////////
//  GIFImage.cs
//  Implementation of the Class GIFImage
//  Generated by Enterprise Architect
//  Created on:      11-5月-2021 12:27:16
//  Original author: Ren
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ShowImageDemo;
namespace ShowImageDemo
{
    public class GIFImage : IPainImage
    {
        /// <summary>
        /// 完成绘图,图片显示
        /// </summary>
        /// <param name="m"></param>
        public void DoPain(Matrix m)
        {
            Console.WriteLine("这里通过接收到像素矩阵后,完成了对GIF图片的显示！");
        }

    }//end GIFImage

}//end namespace ShowImageDemo