///////////////////////////////////////////////////////////
//  IPainImage.cs
//  Implementation of the Interface IPainImage
//  Generated by Enterprise Architect
//  Created on:      11-5月-2021 12:27:21
//  Original author: Ren
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using ShowImageDemo;
namespace ShowImageDemo
{
    public interface IPainImage
    {
        /// <summary>
        /// 在此处完成图片的绘画
        /// </summary>
        /// <param name="m"></param>
        void DoPain(Matrix m);
    }//end IPainImage

}//end namespace ShowImageDemo