///////////////////////////////////////////////////////////
//  Matrix.cs
//  Implementation of the Class Matrix
//  Generated by Enterprise Architect
//  Created on:      11-5月-2021 12:27:20
//  Original author: Ren
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace ShowImageDemo
{
    /// <summary>
    /// 该方法,主要用于将文件进行转换成像素矩阵,供后方图片显示使用
    /// </summary>
    public class Matrix
    {

    }//end Matrix

}//end namespace ShowImageDemo