///////////////////////////////////////////////////////////
//  PNGImage.cs
//  Implementation of the Class PNGImage
//  Generated by Enterprise Architect
//  Created on:      11-5月-2021 12:27:18
//  Original author: Ren
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ShowImageDemo;
namespace ShowImageDemo
{
    public class PNGImage : IPainImage
    {
        /// <summary>
        /// 完成绘制,图片显示
        /// </summary>
        /// <param name="m"></param>
        public void DoPain(Matrix m)
        {
            Console.WriteLine("这里通过接收到像素矩阵后,完成了对PNG图片的显示！");
        }

    }//end PNGImage

}//end namespace ShowImageDemo