///////////////////////////////////////////////////////////
//  Unix.cs
//  Implementation of the Class Unix
//  Generated by Enterprise Architect
//  Created on:      11-5月-2021 12:27:13
//  Original author: Ren
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ShowImageDemo;
namespace ShowImageDemo
{
    public class Unix : MySystems
    {


        public override void ParseFile(string fileName)
        {
            //模拟解析图片，返回像素矩阵m
            Matrix m = new Matrix();
            Console.WriteLine("Unix系统中，将{0}转换成了像素矩阵：", fileName);
            image.DoPain(m);        //在这里调用父类中image中的绘画功能,完成绘画.

        }

    }//end Unix

}//end namespace ShowImageDemo